version: '3'

networks:
  node-network:
    driver: bridge   

services:
  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: db
    networks:
      - node-network    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: app_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always  
    tty: true
    ports:
      - "3306:3306"
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app:/usr/src/app
    networks:
      - node-network       
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=app_db
    restart: always  
    tty: true        
    ports:
      - "3000:3000"            
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-network       
    ports:
      - "8080:80"
    depends_on:
      - db
      - app            